function sleep(n)
  os.execute("sleep " .. tonumber(n))
end
print("Shutting down... ")
sleep(5)
os.execute("clear")
print("It is now safe to turn off your computer.")
sleep(5)
print("[continue]")
io.read("*l")
os.execute("lua root/main/pebble.lua")