-- pebble latest
-- samrcode on GitHub and repl.it
os.execute("clear")
print("[32;7m== latest ==[0m\n")
print("> v1.1.0: The [31mC[32mo[33ml[34mo[35mu[36mr[0m Update!")
print("v1.1, aka The Colour Update, is a cool update that adds colour to all of pebble.")
print("Here is the colour scheme used throughout pebble: ")
print("Title Bars: [32;7mGreen Inverse[0m")
print("Standard Text: White (like always)")
print("List Items: [34m[1] [4mBlue Underline[0m")
print("Tips: [35mMagenta[0m")
print("Notes: [33mYellow[0m")
print("Errors: [31mRed[0m")
print("Continue: [36mCyan[0m")
print("You can find all the colours at root/main/c.txt")
print("We are currently implementing a formatted print module to easily use these colours.")
print("[36m[continue][0m")
io.read("*l")
os.execute("lua root/main/pebble.lua")
